# Generated by Django 4.2.7 on 2023-11-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128)),
                ('request_id', models.CharField(default='', max_length=64)),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('I', 'IN PROGRESS'), ('S', 'SUCCESS'), ('F', 'FAILURE')], default='PENDING', max_length=30)),
                ('more_info', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('total_voters', models.IntegerField()),
                ('book_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
