# Generated by Django 4.2.7 on 2023-11-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
